# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgKPD97CwiiLwyGDgBpcaAk9lTpp-XUB
"""

codigo = """
print("Servidor listo")
"""

with open("app.py", "w") as f:
    f.write(codigo)